name: Go
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - run: ./build.bash setup
      - run: ./build.bash build
      - run: ./build.bash release
        env:
          GITHUB_TOKEN: ${{ secrets.GOTIP_TOKEN }}
